#!/bin/sh
# genbox.sh - generate the aruu-box dispatch table
#
# does one thing: given a list of object file paths on argv, each one
# of BOX_OBJ's own outputs (".box/cmd/<category>/<tool>.o"), emit the c
# source for aruu-box's dispatch table and main() on stdout
#
set -e

[ $# -gt 0 ] || {
        printf "genbox: no object paths given\n" >&2
        exit 1
}

# derive category, tool basestem, and c symbol from one BOX_OBJ output
# path. the symbol transform (tr '.-' '__', append _main) must match
# BOX_OBJ's own objcopy step exactly, see the CATEGORY_OF/symbol
# comment in ninqu.rules for why this is a shell transform and not a
# map
path_category() {
        rest=${1#.box/cmd/}
        printf "%s\n" "${rest%%/*}"
}

path_tool() {
        rest=${1##*/}
        printf "%s\n" "${rest%.o}"
}

path_symbol() {
        tool=$(path_tool "$1")
        printf "%s\n" "$(echo "$tool" | tr '.-' '__')_main"
}

cat << 'HEAD'
/* this file is autogenerated by genbox.sh. do not edit */

# include "wexec.h"
# include "util.h"

# include <stdio.h>
# include <stdlib.h>
# include <string.h>
# include <unistd.h>

HEAD

# extern decls, in the order ninqu passed the objects in (BOX_OBJ's
# own glob order, one category at a time)
for obj in "$@"; do
        sym=$(path_symbol "$obj")
        echo "int ${sym}(int, char **);"
done

cat << 'MID'

struct Cmd {
        const char *name;
        int (*fn)(int, char **);
        const char *category;
};

static struct Cmd cmds[] = {
MID

categories=$(
        for obj in "$@"; do
                path_category "$obj"
        done | sort -u
)

for category in $categories; do
        for obj in "$@"; do
                [ "$(path_category "$obj")" = "$category" ] || continue
                tool=$(path_tool "$obj")
                sym=$(path_symbol "$obj")
                printf '\t{ "%s", %s, "%s" },\n' "$tool" "$sym" "$category"
                if [ "$tool" = "test" ]; then
                        printf '\t{ "[", %s, "%s" },\n' "$sym" "$category"
                fi
        done
done

cat << 'TAIL'
        { NULL, NULL, NULL }
};

static void
usage(void)
{
        struct Cmd *c;
        const char *last;
        int col;

        last = NULL;
        col = 0;
        fprintf(stderr, "usage: %s [-i path] [command [args...]]\n", argv0);
        for (c = cmds; c->name; c++) {
                if (!last || strcmp(c->category, last) != 0) {
                        if (last)
                                fprintf(stderr, "\n\n");
                        last = c->category;
                        fprintf(stderr, "%s:\n", last);
                        col = 0;
                }
                if (col == 0) {
                        fprintf(stderr, "\t%s", c->name);
                        col = 8 + strlen(c->name);
                } else if (col + 2 + strlen(c->name) >= 78) {
                        fprintf(stderr, ",\n\t%s", c->name);
                        col = 8 + strlen(c->name);
                } else {
                        fprintf(stderr, ", %s", c->name);
                        col += 2 + strlen(c->name);
                }
        }
        if (last)
                fputc('\n', stderr);
        exit(1);
}

static void
x_install(const char *path)
{
        struct Cmd *c;
        char buf[4096];
        int r;

        for (c = cmds; c->name; c++) {
                r = snprintf(buf, sizeof buf, "%s/%s", path, c->name);
                if (r < 0 || r >= (int)sizeof buf)
                        eprintf("install: '%s/%s': path too long\n", path, c->name);
                remove(buf);
                if (symlink("aruu-box", buf) < 0)
                        eprintf("install: symlink '%s':", buf);
        }
}

int
main(int argc, char *argv[])
{
        struct Cmd *c;
        char *s;

        argv0 = argv[0];

        for (c = cmds; c->name; c++)
                wexec_register(c->name, c->fn);

        s = strrchr(argv[0], '/');
        if (s)
                s++;
        else
                s = argv[0];

        if (strcmp(s, "aruu-box") == 0) {
                if (argc < 2)
                        usage();
                argc--;
                argv++;
                if (strcmp(argv[0], "-i") == 0) {
                        if (argc < 2)
                                eprintf("usage: aruu-box -i path\n");
                        x_install(argv[1]);
                        return 0;
                }
                s = strrchr(argv[0], '/');
                if (s)
                        s++;
                else
                        s = argv[0];
        }
        for (c = cmds; c->name; c++) {
                if (strcmp(c->name, s) == 0) {
                        argv0 = (char *)c->name;
                        argv[0] = (char *)c->name;
                        return c->fn(argc, argv);
                }
        }
        enprintf(127, "%s: not found\n", s);
        return 1;
}
TAIL
